Tilgungsplan für Bausparvertrag mit Vorausdarlehen liefern
europace/bausparkassen-market-engine-api pull request #24
Opened 2019-07-12 12:15 UTC by larsp79

https://trello.com/c/MeH0TecV

2019-07-12 12:16 UTC, larsp79 commented
erster Entwurf zur Diskussion und Verfeinerung der API @dnltsk @SpinGit

2019-07-12 14:54 UTC, SpinGit requested changes

2019-07-12 14:54 UTC, SpinGit commented on swagger.yml
> +            maximum: 2100
Wollen wir wirklich das Jahr beschränken?

2019-07-12 14:54 UTC, SpinGit commented on swagger.yml
> +        $ref: '#/definitions/euro'
Es heißt: `gesamtkreditbetrag` oder `monatlicheGesamtRate`, hier hast du dich aber an dem Spaltennaming von Sandra gehalten, oder?

2019-07-15 09:32 UTC, larsp79 commented on swagger.yml
> +            maximum: 2100
das macht es auf jeden Fall klar, dass wir eine Angabe aus dem 21. Jahrhundert erwarten

2019-07-15 09:38 UTC, larsp79 commented on swagger.yml
> +        $ref: '#/definitions/euro'
angepasst um konsistenter zum Rest der API zu sein

2019-07-15 09:42 UTC, dnltsk commented on swagger.yml
> +            maximum: 2100
Sollten dann nicht alle Raten, Zinsen usw. auch ein minimum: 0.01 bekommen?

2019-07-15 09:46 UTC, SpinGit commented on swagger.yml
> +            maximum: 2100
Sehe ich als sehr inkonsequent. Wenn ein min und max, dann überall oder eben nicht. Den Wertebereich gibst du ja schon durch den Typ `integer` vor. Willst du ein Jahr enforcen, dann macht sich ein Pattern besser, als ein min oder max. 

Finde das vorgehen generell zu restriktiv.

2019-07-15 12:19 UTC, larsp79 commented on swagger.yml
> +            maximum: 2100
bei einem `integer` macht ein Pattern nicht wirklich Sinn

2019-07-15 12:27 UTC, larsp79 commented
> Sollten dann nicht alle Raten, Zinsen usw. auch ein minimum: 0.01 bekommen?

einige der Werte sind negativ und einige Positiv. Zinsen konkret können auch negativ werden oder ausgesetzt werden.

Um das in Swagger korrekt abzubilden, müssten wir sowas wie `EuroPositiv` und `EuroNegativ` als zusätzliche Typen definieren da bei einem ref keine zusätzlichen Properties erlaubt sind.

Das macht aus meiner Sicht die API schwerer zu verstehen.

2019-07-15 12:28 UTC, larsp79 commented on swagger.yml
> +            maximum: 2100
> Wertebereich gibst du ja schon durch den Typ integer vor

und mit der Beschränkung wird klarer, dass wir 2019 und nicht 19 wollen

2019-07-15 15:50 UTC, SpinGit commented on swagger.yml
> +            maximum: 2100
Wie du möchtest. GEFN. Von daher lass uns mit der API starten. Wird sich eh bei der Verwendung härten.

2019-07-15 15:50 UTC, SpinGit submitted a review, later dismissed

2019-07-16 15:19 UTC, larsp79 commented
@SpinGit @dnltsk die Readme wurde noch um ein Beispiel ergänzt und die Werte zum Ende der Spar-/Darlehensphase wurden umbenannt um klarer zu machen, dass es sich hier nicht um Summen handelt

2019-07-17 07:00 UTC, SpinGit approved these changes

2019-07-17 07:20 UTC, merged

2019-08-07 08:53 UTC, larsp79 commented
resolves #13