Beispiel requests
europace/bausparkassen-market-engine-api pull request #33
Opened 2019-09-16 06:54 UTC by dnltsk

Trello Karte: https://trello.com/c/lryXnVrf/250-beispiele-im-api-projekt-anlegen

Tildungsplan und Bontätscheck im Response sind stets dabei.

2019-09-16 08:05 UTC, huehnerlady commented
Da @larsp79 die Beispiele angefordert hat macht es meiner meinung nach sinn, wenn er reviewt, weil ich nicht weiß was für Ansprüche gestellt wurden

2019-09-16 08:46 UTC, larsp79 commented
der Anspruch ist zukünftige Fragen zur API zu minimieren und den Einstieg zu erleichtern

2019-09-16 09:13 UTC, larsp79 requested changes

2019-09-16 09:13 UTC, larsp79 commented on README.md
> +      "id": "...",
Beispiel repräsentativ gestalten

```suggestion
      "id": "68c346d6-58fc-4e3d-ab13-d39c4bcf00f0",
```

2019-09-16 09:13 UTC, larsp79 commented on README.md
> +        "wohnart": "IM_EIGENEN_HAUS",
dies ist keine minimale Anfrage

neuen Beispielfall verwenden, bei dem nur kreditbetrag und laufzeit angegeben wurde

2019-09-16 09:13 UTC, larsp79 commented on README.md
> +    {
Toggles im Beispiel als leere Liste belassen

2019-09-16 09:13 UTC, larsp79 commented on README.md
> +      "vertriebsgruppe": "creditfair"
hier etwas allgemeiner werden

```suggestion
      "vertriebsgruppe": "Beispielgruppe"
```

2019-09-16 09:14 UTC, larsp79 commented
die readme wird so schon relativ umfangreich, evtl die Beispiele in eine examples.md auslagern und nur in der Readme verlinken

2019-09-16 09:15 UTC, larsp79 commented
ein Beispiel für ein angenommes Angebot rundet fehlt noch um das Ganze abzurunden denke ich

2019-09-17 09:30 UTC, larsp79 commented on beispiele.md
> +        "beschaeftigungsverhaeltnis": "ANGESTELLT",
das hier ist noch nicht der minimale Request da hier noch Infos wie Beschäftigung und wohnart gesetzt sind

2019-09-17 09:31 UTC, larsp79 commented on beispiele.md
> +        "beschaeftigungsverhaeltnis": "ANGESTELLT",
ich vermute mal das kommt noch

2019-09-17 13:06 UTC, dnltsk commented
@larsp79 bitte nochmal rüberschauen.

2019-09-18 14:56 UTC, dnltsk commented
branch wird erstmal gelöscht.

2019-09-18 14:56 UTC, closed without merging