ReviewMitPullRequest
europace/bausparkassen-market-engine-api pull request #4
Opened 2018-11-06 11:52 UTC by gomil

2018-11-13 10:04 UTC, gomil commented
@larsp79 mir ist grade aufgefallen, dass die Trennung in mehrere Bausteine noch nicht enthalten ist - von daher kannst du das Angebot erstmal noch aus dem Review ausklammern, bis ich das mit Sandra geklärt habe

2018-11-22 15:45 UTC, larsp79 requested changes
- diverse Typen per Ref rausziehen um passende Namen bei der Codegenerierung zu erhalten
- diverse Verbesserungen/Fehler in der API

@gomil wenn du keinen Einwand hast, ziehe ich erstmal die Typen als Refs raus

2018-11-22 15:45 UTC, larsp79 commented on swagger.yml
> +      bonitaetscheck:
als ref rausziehen

2018-11-22 15:45 UTC, larsp79 commented on swagger.yml
> +      bonitaetscheck:
mit den aktuellen Properties auch eher spezifisch für eine Haushaltsrechnung

siehe auch #3

2018-11-22 15:45 UTC, larsp79 commented on swagger.yml
> +      bonitaetscheck:
entweder spezifisch für Haushaltsrechnung umbenennen oder mehr in Richtung generische Übersicht, wie auch ME intern verwendet.

2018-11-22 15:45 UTC, larsp79 commented on swagger.yml
> +          anzahlKinder:
brauchen wir hier auch die Unterscheidung Gesamtanzahl vs nur unterhaltsberechtigte?

2018-11-22 15:45 UTC, larsp79 commented on swagger.yml
> +          anzahlKinder:
hier auch eine Liste von Kindern verwenden?

2018-11-22 15:45 UTC, larsp79 commented on swagger.yml
> +      positionen:
hier erzeugt die Codegenerierung den unschönen Typen BonitaetscheckPositionPositionen.

Umstrukturieren um bessere verständliche Namen zu bekommen.

2018-11-22 15:45 UTC, larsp79 commented on swagger.yml
> +      beschaeftigungsverhaeltnis:
erzeugt bei Codegenerierung Inner Enum Klassen. Wollen wir das?

2018-11-22 15:45 UTC, larsp79 commented on swagger.yml
> +        type: string
Format für Base64 Kodierung angeben

```suggestion
        type: string
        format: byte
```

2018-11-22 15:45 UTC, larsp79 commented on swagger.yml
> +      monatlicheEinnahmen:
als Ref rausziehen. Unschöner generierter Klassenname.

2018-11-22 15:45 UTC, larsp79 commented on swagger.yml
> +      jaehrlicheEinnahmen:
als Ref rausziehen. Unschöner generierter Klassenname.

2018-11-22 15:45 UTC, larsp79 commented on swagger.yml
> +          einkommenAusSelbstaendigkeit:
als Ref rausziehen. Unschöner generierter Klassenname.

2018-11-22 15:45 UTC, larsp79 commented on swagger.yml
> +          mietUndPachteinnahmen:
als Ref rausziehen. Unschöner generierter Klassenname.

2018-11-22 15:45 UTC, larsp79 commented on swagger.yml
> +      haushalt:
es kann mehrere Haushalte geben

2018-11-22 15:45 UTC, larsp79 commented on swagger.yml
> +    type: string
Format mit angeben

```suggestion
    type: string
    pattern: '^[A-Z]{2}$'
```

2018-11-22 15:45 UTC, larsp79 commented on swagger.yml
> +  prozent:
value Property ist hier unnötig kompliziert

einfacher so schreiben

```
  prozent:
    type: number
    description: 100 basierter Prozentwert mit bis zu 2 Nachkommastellen
    format: 'xxx.xx'
```

2018-11-22 15:45 UTC, larsp79 commented on swagger.yml
> +  euro:
value Property ist hier unnötig kompliziert

einfacher so schreiben

```
  euro:
    type: number
    description: Euro-Betrag mit bis zu 2 Nachkommastellen
    format: 'xxx.xx'
```

2018-11-22 15:45 UTC, larsp79 commented on swagger.yml
> +      fahrzeugleistung:
als ref rausziehen, ergibt aktuell unschönen Namen bei Codegenerierung

2018-11-22 15:45 UTC, larsp79 commented on swagger.yml
> +      type: object
`FeatureToggle` als ref definieren, aktuell wird `FeatureTogglesInner` bei der Codegenerierung erzeugt

2018-11-22 15:45 UTC, larsp79 commented on swagger.yml
> +      kreditwunsch:
als ref rausziehen, unschöner generierter Code

2018-11-22 15:45 UTC, larsp79 commented on swagger.yml
> +      abzuloesendeVerbindlichkeiten:
als ref rausziehen, unschöner generierter Code

2018-11-22 15:45 UTC, larsp79 commented on swagger.yml
> +      partnerKennzeichen:
als ref rausziehen, unschöner generierter Code

2018-11-22 15:45 UTC, larsp79 commented on swagger.yml
> +      partnerKennzeichen:
vom Inhalt her sind das eher produktanbieterspezifische Parameter

Vorschlag: `ProduktanbieterParameter`

2018-11-22 15:45 UTC, larsp79 commented on swagger.yml
> +    description: 100 basierter Prozentwert mit bis zu 2 Nachkommastellen
Prozentwerte sind in unseren bisherigen APIs der ME immer 1 basiert

```suggestion
    description: 1 basierter Prozentwert mit bis zu 4 Nachkommastellen
```

2018-11-22 15:45 UTC, larsp79 commented on swagger.yml
> +        format: 'xxx.xx'
```suggestion
        format: 'x.xxxx'
```

2018-11-22 15:45 UTC, larsp79 commented on swagger.yml
> +      gemeinsameAntragstellerangaben:
als Ref rausziehen

2018-11-22 15:45 UTC, larsp79 commented on swagger.yml
> +      aufenthaltstitel:
als Ref rausziehen

2018-11-22 15:45 UTC, larsp79 commented on swagger.yml
> +      anzahlPersonenImHaushalt:
da wir in der API einen Haushalt haben, sollte das dann da stehen da passendere Stelle

Wollen wir den Haushalt in der API generell?

2018-11-28 13:53 UTC, larsp79 commented on swagger.yml
> +      beschaeftigungsverhaeltnis:
Enum als ref rausgezogen

2018-12-06 16:06 UTC, larsp79 commented on swagger.yml
> +  bonitaetscheck:
@gomil überarbeitete Version der Übersicht um auch verschiedene Übersichtsarten abbilden zu können

2018-12-07 15:41 UTC, merged