weitere Angaben zu Verbindlichkeiten und Vermögen
europace/bausparkassen-market-engine-api pull request #9
Opened 2019-01-09 14:55 UTC by larsp79

2019-01-10 09:34 UTC, larsp79 commented on swagger.yml
> -      abloesebetrag:
jeweils entfernt, da es der Restschuld entspricht

2019-01-11 22:09 UTC, gomil requested changes
Deine Änderungen passen - habe noch einen Punkt unabhängig davon angemerkt

2019-01-11 22:09 UTC, gomil commented on swagger.yml
>        wohnflaecheEigengenutzterImmobilieInQm:
die wohnflaeche passt irgendwie nicht richtig unter vermoegen - vielleicht mit den restlichen Immobilien-Angaben in einen eigenen Typen?

2019-01-11 22:09 UTC, gomil commented on swagger.yml
> -      abloesebetrag:
gut gesehen 👍

2019-01-14 08:57 UTC, larsp79 commented on swagger.yml
>        wohnflaecheEigengenutzterImmobilieInQm:
hab die redundanten Immobilienangaben direkt unter Vermögen entfernt @gomil

2019-01-15 10:18 UTC, gomil commented on swagger.yml
>        wohnflaecheEigengenutzterImmobilieInQm:
@larsp79 stimmt ist ja redundant: gesamt-wohnfläche und die selbstgenutzte wohnfläche ist angegeben, dann kann man auf die eigengenutzte zurückschließen

2019-01-15 10:18 UTC, gomil approved these changes

2019-01-15 10:33 UTC, merged